### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Yoll28** [The-Boss-Hacker/BossAdv#2]
![9AD95AA3-69B3-4B04-9846-17D5B7EF5E3B](https://user-images.githubusercontent.com/107960255/181847571-c61be29d-96ca-4dec-bbfd-403cf84c67f1.png)

Why the link be like this?

**Comment by The-Boss-Hacker** [comment]
Turn On Hotspot

**Comment by Yoll28** [comment]
Ok mantap tq
