### ISSUE TITLE
A request to remove the hostspot glitch. 

### ISSUE THREAD

**Issue by khansaad1275** [The-Boss-Hacker/BossAdv#3]
Since we are using Cloudflare for tunnelling and not ngrok, we don't have to use data and hotspot option, because cloudflared doesn't require that. Also, can we get localhost link too? I mean, just in case Cloudflare is not working, we can try to port forward with different tool? by the way i have added your tool in on of my post and given you a back link <3 here is the link if you wanna check it out.  https://www.learntermux.tech/2020/10/Install-and-use-ADVPhishing-Tool-Termux.html

**Comment by The-Boss-Hacker** [comment]
> Since we are using Cloudflare for tunnelling and not ngrok, we don't have to use data and hotspot option, because cloudflared doesn't require that. Also, can we get localhost link too? I mean, just in case Cloudflare is not working, we can try to port forward with different tool? by the way i have added your tool in on of my post and given you a back link <3 here is the link if you wanna check it out. https://www.learntermux.tech/2020/10/Install-and-use-ADVPhishing-Tool-Termux.html


**Termux Problem And Some Device Work All Tunnels Without Hotspot** 

**All Tunnels I Am Tested Required Hotspot To Work Only In Termux**

**Or**

**Install  Kali or Ubuntu in Termux Without Hotspot Run The Tool Working💯 **
