### ISSUE TITLE
link not created

### ISSUE THREAD

**Issue by aamerF** [The-Boss-Hacker/BossAdv#6]
kindly support 

![Capture](https://user-images.githubusercontent.com/48980882/196253670-5c7a0b1d-01b2-46ce-b532-9e889c43225f.PNG)

**Comment by The-Boss-Hacker** [comment]
> This Tool Is Working ✅

> I Am Tested ✅

![Screenshot_20221204_134601](https://user-images.githubusercontent.com/107553476/205481068-3bcd8fc9-84cb-4e67-bd49-674469579d53.jpg)
> With OTP Working ✅
![Screenshot_20221204_134636](https://user-images.githubusercontent.com/107553476/205481063-a35d5c7c-e4cf-4764-adef-19244a67d0c0.jpg)

> Installation Error ❌

> Installation Fail ❌

> Package Error ❌

> Installing Time Internet Auto Off ❌

> More Issues ❌

> Reinstall This Tool ✅

**Comment by The-Boss-Hacker** [comment]
Fixed
