### ISSUE TITLE
About modifying server and domain name

### ISSUE THREAD

**Issue by mozhu-too** [The-Boss-Hacker/BossAdv#8]
Very nice work, I would like to know if it is possible to customize my own server and domain name. Can I write the website I want to copy by myself? If it is convenient, I can say it here. If it is not convenient, can I add a contact method?

**Comment by mozhu-too** [comment]
yes，can

**Comment by The-Boss-Hacker** [comment]
`give me number`

**Comment by The-Boss-Hacker** [comment]
[`Whatsapp`](https://wa.me/+917994186084)  `Message now`
